name: flusseract
description: "Flutter plugin for Tesseract OCR library."
version: 0.0.1
homepage: "https://github.com/letterassist-ai/flusseract"

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  logging: ^1.2.0
  image: ^4.1.4
  ffi_helper_ab: ^0.0.1

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
