name: flusseract
description: "Flutter plugin for the Tesseract OCR library."
version: 0.1.2
homepage: "https://github.com/letterassist-ai/flusseract"

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.2
  ffi_helper_ab: ^0.0.2
  path_provider: ^2.1.2
  logging: ^1.2.0

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
